### ISSUE TITLE
Feature and Balance Suggestions!

### ISSUE THREAD

**Issue by pcrain** [pcrain/GungeonCraft#1]
Feel free to comment with suggestions down below! :smile:

**Comment by Noirakka** [comment]
soul kaliber with hot lead (fire shot) causes heavy lag when enemies on fire
![image](https://github.com/pcrain/GungeonCraft/assets/88335812/77bed804-13bd-4b2f-a957-b0af5bfb0e7c)

**Comment by pcrain** [comment]
> soul kaliber with hot lead (fire shot) causes heavy lag when enemies on fire ![image](https://user-images.githubusercontent.com/88335812/277090687-77bed804-13bd-4b2f-a957-b0af5bfb0e7c.png)

Fixed! :smiley:

**Comment by Antiiilluminati** [comment]
When you kill the boss with the Quarter Pounder, the golden sprite sinks into the lava and locks the player into "cutscene mode" where you cant move, shoot, look around, access menus, or do anything. (it's not because I'm stuck in the pedestal)
![20240324193233_1](https://github.com/pcrain/GungeonCraft/assets/164813181/9738f32c-de63-4814-8154-d87860920ccc)

**Comment by pcrain** [comment]
> When you kill the boss with the Quarter Pounder, the golden sprite sinks into the lava and locks the player into "cutscene mode" where you cant move, shoot, look around, access menus, or do anything. (it's not because I'm stuck in the pedestal) ![20240324193233_1](https://private-user-images.githubusercontent.com/164813181/316351788-9738f32c-de63-4814-8154-d87860920ccc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzE5MDMsIm5iZiI6MTcxMTM3MTYwMywicGF0aCI6Ii8xNjQ4MTMxODEvMzE2MzUxNzg4LTk3MzhmMzJjLWRlNjMtNDgxNC04MTU0LWQ4Nzg2MDkyMGNjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMzAwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjAwNTkyMzU0OTNhZGNmZGI2NGZmOTA3ZTAwOTM2ZWJkZmI0M2E3ZGMxMzk3ZDYwM2M1YWIyNmFlNjQ0MTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j6yF75v8_jmcOrXNCd15rasFxd2ge_n_0kAPf468vSM)

...whoops, I shall fix that :sweat_smile: Thanks for the report! :slightly_smiling_face:

**Comment by Antiiilluminati** [comment]
Thanks for fixing! This mod is definitely my favorite out of all of the ETG mods!
