### ISSUE TITLE
Yggdrashell Bug: Earth Armor Breaks Due to Electrification Despite Robot's Electrical Resistance & Leaves Not Disappearing

### ISSUE THREAD

**Issue by dIDMas** [pcrain/GungeonCraft#12]
Hey pcrain,

I've encountered an issue while playing with the Yggdrashell, where the Earth Armor worn by the robot breaks when electrified. Given that the robot has electrical resistance, I believe this behavior might be unintended.

In my second playthrough, I also noticed that the leaves of the Yggdrashell are not disappearing as they should. Instead, they are stuck in place, filling the entire room with green.

https://github.com/user-attachments/assets/e36167cf-530e-4913-a43b-1d99dbdf674a

**Comment by pcrain** [comment]
Ah those are both pretty bad, yikes. :grimacing: I'll have them both fixed by next update, hopefully tomorrow.

**Comment by pcrain** [comment]
Fixed, thanks for the report! :smile:
