### ISSUE TITLE
Yggdrashell bug

### ISSUE THREAD

**Issue by 59160153** [pcrain/GungeonCraft#13]
![20240922130906_1](https://github.com/user-attachments/assets/91291f54-35bf-42c9-9b8a-7adeef5b931f)
1.19 update, The vine firing point of this gun is fixed in place，It cannot be used normally either

**Comment by pcrain** [comment]
Ah crap, looking into it. :fearful:

**Comment by pcrain** [comment]
@59160153 I'm not actually able to reproduce this, can you describe all the steps you took starting from the beginning of your run (or even better, from launching the game) to get to this state?

Also, if it's available and if you haven't started a new run since this happened, can you please send the output log?

```
How to find LogOutput.log

(r2modman, Thunderstore Mod Manager):
1. In your target profile, go to settings.
2. In settings, press "Browse profile folder"
3. In the opened folder, go to the folder named "BepInEx"
4. In there you should find a file named LogOutput.log, that's the file you're looking for.

(no mod manager):
1. Go to your game's directory.
2. Go to the folder named BepInEx.
3. In there you should find a file named LogOutput.log, that's the file you're looking for.
```

**Comment by pcrain** [comment]
Welp, just reproduced it, nevermind. :sweat_smile:

**Comment by pcrain** [comment]
Fixed, thanks for the report! :smile:

**Comment by 59160153** [comment]
I originally saw the update log, so I went straight to the game console and called up this gun to see the new special effects. Then I discovered a major issue with this gun and reported it
I really like this mod, there are many interesting tribute contents that make people smile knowingly. Thank you for your contribution to the mod community of this game

**Comment by 59160153** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17090083/LogOutput.log)

**Comment by pcrain** [comment]
@59160153 Thanks a ton, I managed fix it just a little bit before you posted that. The update's live now. :slightly_smiling_face:
