### ISSUE TITLE
Bullet doesn't fire out the tip of the barrel

### ISSUE THREAD

**Issue by Matt577** [pcrain/GungeonCraft#4]
The bullet that fires out of the Hand Cannon gun does not start from the end of the barrel, it is slightly in front and above your barrel 
![gun2](https://github.com/pcrain/GungeonCraft/assets/79345270/ba3c0170-df49-466f-aaf8-66a0d67b88b2)

**Comment by pcrain** [comment]
Hunh...didn't know about that one. Thanks, it'll be fixed next update. :smile: :heart:
