### ISSUE TITLE
omnidirectional laser keeps firing in the same direction 

### ISSUE THREAD

**Issue by Leol22** [pcrain/GungeonCraft#6]
it worked perfectly in floor 2
https://streamable.com/qx215s

**Comment by pcrain** [comment]
Whoops...yeah it super breaks whenever a new floor loads, my b. :sweat_smile: It'll be fixed in the next update...which should hopefully be tonight! Thanks for the report! :smiley:

**Comment by pcrain** [comment]
Fixed! :smile:
