### ISSUE TITLE
Not all modded characters can use the "Bullet that can kill the future" on themselves

### ISSUE THREAD

**Issue by Uimitorul** [pcrain/GungeonCraft#7]
As of right now i only found 3 modded characters that when you try to use the "Bullet that can kill the future" on them the secret area that you should be teleported to never loads and the game gets stuck on the loading screen (forever most likely), also i did took a look in the logs to see what is going on there but when i get stuck in the loading screen nothing new shows up.

The 3 modded characters that im talking about are:
Modular from the mod "Modular Remastered"
Lamey from the mod "Cut Characters Reborn" (for this mod in particular i would not be surprised if the ninja and the cosmonaut will have the same problem when they will get remade)
Cultist from the mod "SpecialAPIs Stuff"

My guess as of why this happens is maybe, just maybe because this characters have more complicated code then other modded characters out there.

**Comment by pcrain** [comment]
No clue at all why this would be happen, though the three characters you mentioned are CharAPI characters and most other characters are Kyle's Custom Character Mod characters, so that might be related.

I'll look at it in the near future, thanks for the report! :heart: :smile:

**Comment by pcrain** [comment]
Turns out the bug had nothing to do with CCs and is much worse: the floor would completely stop working after returning to the breach for any reason.

Fixed it locally so it should be fixed in the next update. :slightly_smiling_face: I'll close this once the update's live, hopefully some time this weekend.

**Comment by pcrain** [comment]
Fixed! :smile:
